# Generated by Django 5.2.7 on 2025-10-07 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='staff', max_length=100),
            preserve_default=False,
        ),
    ]
